// Generated by `cargo run --release -p jolt-akita --features akita-test-schedules --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules k16_fixture`
#[allow(unused_imports)]
use super::{
    ChunkedWitnessCfg, CommitmentPayloadMode, CommitmentRingDims, CommittedGroupProfile,
    DecompositionParams, GeneratedBlockGeometry, GeneratedCommittedGroup,
    GeneratedFoldScheduleEntry, GeneratedInnerCommitMatrix, GeneratedOpenCommitMatrix,
    GeneratedOuterCommitMatrix, GeneratedRecursiveFold, GeneratedRootFinalGroup, GeneratedRootFold,
    GeneratedRootPrecommittedGroup, GeneratedScheduleCatalogIdentity, GeneratedSetupPrefixInput,
    GeneratedTerminalFold, GeneratedWitnessPartition, InnerCommitMatrixParams,
    OuterCommitMatrixParams, PlannerCostModelId, PolynomialGroupLayout, RingDimensionScheduleMode,
    SelectionPolicyId, SelectiveL2ResponseModelId, SisL2TableDigest, SisModulusProfileId,
    SisSecurityPolicyId, SisTableDigest,
};

#[rustfmt::skip]
pub(crate) static JOLT_FP128_ONEHOT_K16_FIXTURE_SCHEDULES: &[GeneratedFoldScheduleEntry] = &[
    GeneratedFoldScheduleEntry {
        root: GeneratedRootFold {
            final_group: GeneratedRootFinalGroup { layout: PolynomialGroupLayout::new(22, 1), num_digits_inner: 1, num_digits_fold: 2,
                commitment: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 16384, positions_per_block: 1024, live_blocks: 16 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 256, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 } },
            precommitted_groups: &[],
            open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 },
            witness_partition: GeneratedWitnessPartition::Single,
        },
        recursive_folds: &[
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 3620, positions_per_block: 256, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 256, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 7576, positions_per_block: 512, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 5016, positions_per_block: 512, live_blocks: 10 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Raw, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 4056, positions_per_block: 512, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 5 }, outer_slice_count: 1 }, num_digits_fold: 2, response_l2_sq_cap: Some(354872714), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 5 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
        ],
        terminal: GeneratedTerminalFold { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 2012, positions_per_block: 256, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 5 }, num_digits_inner: 1, fold_log_basis: 6, fold_digit_count: 2, inner_output_rank: 3, inner_coeff_linf_bound: 0, response_l2_sq_cap: Some(663986807), z_linf_cap: None, z_rice_low_bits: 7, z_payload_bytes: 22528 },
    },
    GeneratedFoldScheduleEntry {
        root: GeneratedRootFold {
            final_group: GeneratedRootFinalGroup { layout: PolynomialGroupLayout::new(23, 1), num_digits_inner: 1, num_digits_fold: 3,
                commitment: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 32768, positions_per_block: 1024, live_blocks: 32 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 256, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 } },
            precommitted_groups: &[],
            open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 },
            witness_partition: GeneratedWitnessPartition::Single,
        },
        recursive_folds: &[
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 6020, positions_per_block: 512, live_blocks: 12 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 256, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 11055, positions_per_block: 1024, live_blocks: 11 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 4, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 7631, positions_per_block: 512, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: Some(151392887), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Raw, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 3992, positions_per_block: 512, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 5 }, outer_slice_count: 1 }, num_digits_fold: 2, response_l2_sq_cap: Some(328910376), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 5 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
        ],
        terminal: GeneratedTerminalFold { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 2012, positions_per_block: 256, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 5 }, num_digits_inner: 1, fold_log_basis: 6, fold_digit_count: 2, inner_output_rank: 3, inner_coeff_linf_bound: 0, response_l2_sq_cap: Some(661390573), z_linf_cap: None, z_rice_low_bits: 7, z_payload_bytes: 22528 },
    },
    GeneratedFoldScheduleEntry {
        root: GeneratedRootFold {
            final_group: GeneratedRootFinalGroup { layout: PolynomialGroupLayout::new(24, 1), num_digits_inner: 1, num_digits_fold: 3,
                commitment: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 131072, positions_per_block: 2048, live_blocks: 64 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 128, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 2 } },
            precommitted_groups: &[],
            open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 },
            witness_partition: GeneratedWitnessPartition::Single,
        },
        recursive_folds: &[
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 14834, positions_per_block: 1024, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 128, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 10711, positions_per_block: 1024, live_blocks: 11 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 4, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 7631, positions_per_block: 512, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: Some(151392887), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Raw, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 3992, positions_per_block: 512, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 5 }, outer_slice_count: 1 }, num_digits_fold: 2, response_l2_sq_cap: Some(328910376), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 5 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
        ],
        terminal: GeneratedTerminalFold { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 2012, positions_per_block: 256, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 5 }, num_digits_inner: 1, fold_log_basis: 6, fold_digit_count: 2, inner_output_rank: 3, inner_coeff_linf_bound: 0, response_l2_sq_cap: Some(661390573), z_linf_cap: None, z_rice_low_bits: 7, z_payload_bytes: 22528 },
    },
    GeneratedFoldScheduleEntry {
        root: GeneratedRootFold {
            final_group: GeneratedRootFinalGroup { layout: PolynomialGroupLayout::new(25, 1), num_digits_inner: 1, num_digits_fold: 3,
                commitment: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 131072, positions_per_block: 2048, live_blocks: 64 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 256, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 } },
            precommitted_groups: &[],
            open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 },
            witness_partition: GeneratedWitnessPartition::Single,
        },
        recursive_folds: &[
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 47375, positions_per_block: 2048, live_blocks: 24 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 4, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 15081, positions_per_block: 1024, live_blocks: 15 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 6552, positions_per_block: 512, live_blocks: 13 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: Some(533363791), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Raw, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 3736, positions_per_block: 512, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 5 }, outer_slice_count: 1 }, num_digits_fold: 2, response_l2_sq_cap: Some(319174499), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 5 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
        ],
        terminal: GeneratedTerminalFold { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 2012, positions_per_block: 256, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 5 }, num_digits_inner: 1, fold_log_basis: 6, fold_digit_count: 2, inner_output_rank: 3, inner_coeff_linf_bound: 0, response_l2_sq_cap: Some(661390573), z_linf_cap: None, z_rice_low_bits: 7, z_payload_bytes: 22528 },
    },
    GeneratedFoldScheduleEntry {
        root: GeneratedRootFold {
            final_group: GeneratedRootFinalGroup { layout: PolynomialGroupLayout::new(26, 1), num_digits_inner: 1, num_digits_fold: 3,
                commitment: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 524288, positions_per_block: 4096, live_blocks: 128 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 128, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 2 } },
            precommitted_groups: &[],
            open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 },
            witness_partition: GeneratedWitnessPartition::Single,
        },
        recursive_folds: &[
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 58468, positions_per_block: 2048, live_blocks: 29 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_slice_count: 1 }, num_digits_fold: 4, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 3 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 16371, positions_per_block: 1024, live_blocks: 16 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 3 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: None, open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Compressed, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 6744, positions_per_block: 512, live_blocks: 14 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_slice_count: 1 }, num_digits_fold: 3, response_l2_sq_cap: Some(562571422), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 4 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
            GeneratedRecursiveFold { payload_mode: CommitmentPayloadMode::Raw, witness: GeneratedCommittedGroup { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 3864, positions_per_block: 512, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 4 }, outer_commit_matrix: GeneratedOuterCommitMatrix { ring_dimension: 64, log_basis: 5 }, outer_slice_count: 1 }, num_digits_fold: 2, response_l2_sq_cap: Some(333453785), open_commit_matrix: GeneratedOpenCommitMatrix { ring_dimension: 64, log_basis: 5 }, incoming_setup_prefix: None, witness_partition: GeneratedWitnessPartition::Single },
        ],
        terminal: GeneratedTerminalFold { geometry: GeneratedBlockGeometry { live_ring_elements_per_claim: 2012, positions_per_block: 256, live_blocks: 8 }, inner_commit_matrix: GeneratedInnerCommitMatrix { ring_dimension: 64, log_basis: 5 }, num_digits_inner: 1, fold_log_basis: 6, fold_digit_count: 2, inner_output_rank: 3, inner_coeff_linf_bound: 0, response_l2_sq_cap: Some(661390573), z_linf_cap: None, z_rice_low_bits: 7, z_payload_bytes: 22528 },
    },
];

#[rustfmt::skip]
pub(crate) static CATALOG_SUFFIX_DIMENSIONS: &[usize] = &[64];
#[rustfmt::skip]
pub(crate) static CATALOG_POTENTIAL_A_DIMENSIONS: &[usize] = &[64, 128, 256];
#[rustfmt::skip]
pub(crate) static CATALOG_POTENTIAL_B_DIMENSIONS: &[usize] = &[64, 128];
#[rustfmt::skip]
pub(crate) static CATALOG_POTENTIAL_D_DIMENSIONS: &[usize] = &[64, 128];
#[rustfmt::skip]
pub(crate) static CATALOG_RING_DIMENSIONS: &[usize] = &[64, 128, 256];
#[rustfmt::skip]
pub(crate) static CATALOG_IDENTITY: GeneratedScheduleCatalogIdentity = GeneratedScheduleCatalogIdentity {
    family_name: "jolt-fp128-onehot-k16-fixture",
    protocol_epoch: 1,
    cost_model: PlannerCostModelId::ExactPayloadAndSetupEnvelope,
    selective_l2_response_model: SelectiveL2ResponseModelId::TypedProtocolMomentsV1,
    selection_policy: SelectionPolicyId::MinSetupMatrixFieldElementsThenProofPayload,
    recursive_split_search_policy: crate::RecursiveSplitSearchPolicy::BoundedBalancedExtremesV1,
    setup_field_budget: None,
    min_offloaded_witness_contraction: 3,
    sis_modulus_profile: SisModulusProfileId::Q128OffsetA7F7,
    sis_security_policy: SisSecurityPolicyId::Quantum128BitADPS16,
    sis_table_digest: SisTableDigest([0xf2, 0xe4, 0x77, 0x6d, 0x21, 0x19, 0xe7, 0x2b, 0xcb, 0x8c, 0x0b, 0x5d, 0x39, 0x0f, 0x93, 0xea, 0x50, 0xa7, 0x07, 0xf2, 0xb2, 0xd2, 0x1d, 0x95, 0x78, 0x67, 0xf9, 0x32, 0x2e, 0x20, 0xe1, 0x6d]),
    sis_l2_table_digest: SisL2TableDigest([0xa1, 0xcc, 0x0a, 0x06, 0x08, 0x97, 0x44, 0x14, 0x5b, 0x61, 0x91, 0x9c, 0xf0, 0x01, 0xea, 0x26, 0x0c, 0x95, 0xa4, 0xbb, 0xa1, 0x61, 0xff, 0xda, 0xff, 0x55, 0x39, 0x1d, 0x0d, 0xfa, 0x10, 0x2a]),
    uniform_ring_dimension: 256,
    setup_prefix_inner_ring_dimension: 256,
    decomposition: DecompositionParams { log_basis: 3, log_commit_bound: 1, log_open_bound: Some(128) },
    claim_ext_degree: 1,
    chal_ext_degree: 1,
    inner_basis_range: (3, 11),
    opening_basis_range: (3, 6),
    witness_chunk: ChunkedWitnessCfg { num_chunks: 1, num_activated_levels: 0 },
    recursive_setup_planning: false,
    ring_dimension_schedule_mode: RingDimensionScheduleMode::AdaptiveDimension { num_search_levels: 2, suffix_dimensions: CATALOG_SUFFIX_DIMENSIONS, potential_a_dimensions: CATALOG_POTENTIAL_A_DIMENSIONS, potential_b_dimensions: CATALOG_POTENTIAL_B_DIMENSIONS, potential_d_dimensions: CATALOG_POTENTIAL_D_DIMENSIONS },
    ring_dimensions: CATALOG_RING_DIMENSIONS,
    ring_challenge_config_digest: 3458533356553718245,
    key_count: 5,
    key_digest: 601363110268295630,
};
