[package]
name = "pairing-msm"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "pairing-msm-guest", path = "./guest" }


